kind: Service
apiVersion: v1
metadata:
  name: payment-service
  labels:
    name: payment-service
spec:
  ports:
    - nodePort: 30169 
      port: 9191      
      targetPort: 9191  
      protocol: TCP
  selector:           
    app: payment-service
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: payment-service
spec:                
  selector:         
    matchLabels:
      app: payment-service
  replicas: 2        
  template:
    metadata:
      labels:        
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: undral23/payment-service
          ports:
            - containerPort: 9191