kind: Service
apiVersion: v1
metadata:
  name: product-service
  labels:
    name: product-service
spec:
  ports:
    - nodePort: 30164
      port: 9002      
      targetPort: 9002  
      protocol: TCP
  selector:           
    app: product-service
  type: NodePort       

---
apiVersion: apps/v1 
kind: Deployment    
metadata:              
  name: product-service
spec:                
  selector:         
    matchLabels:
      app: product-service
  replicas: 2        
  template:
    metadata:
      labels:        
        app: product-service
    spec:
      containers:
        - name: product-service
          image: undral23/product-service
          ports:
            - containerPort: 9002                
          env:   # Setting Enviornmental Variables
          - name: DB_HOST   # Setting Database host address from configMap
            valueFrom: 
              configMapKeyRef:
                name: product-db-conf  # name of configMap
                key: host
          - name: DB_NAME  # Setting Database name from configMap
            valueFrom:
              configMapKeyRef:
                name: product-db-conf 
                key: name
          - name: DB_USERNAME  # Setting Database username from Secret
            valueFrom:
              secretKeyRef:
                name: product-secret # Secret Name
                key: username
          - name: DB_PASSWORD # Setting Database password from Secret
            valueFrom:
              secretKeyRef:
                name: product-secret
                key: password     
        