server:
  port: 9003

spring:
  application:
    name: TRANSACTION-CARD-SERVICE

  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: localhost


jwt:
  secret: admin