INSERT INTO PRODUCT(ID, NAME, VENDOR, PRICE, CATEGORY, AVAILABLE_UNIT) values (1, 'iPhone 8 Plus', 'Apple', 250, 'Phone', 100);
INSERT INTO PRODUCT(ID, NAME, VENDOR, PRICE, CATEGORY, AVAILABLE_UNIT) values (2, 'iPhone 10', 'Apple', 400, 'Phone', 50);
INSERT INTO PRODUCT(ID, NAME, VENDOR, PRICE, CATEGORY, AVAILABLE_UNIT) values (3, 'iPhone 11', 'Apple', 600, 'Phone', 50);