server:
  port: 9002

spring:
  application:
    name: ORDER-SERVICE
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?useSSL=false
#    username: ${DB_USERNAME}
#    password: ${DB_PASSWORD}
#    hikari:
#      initialization-fail-timeout: 0
#    initialization-mode: ALWAYS
#
#  jpa:
#     database-platform: org.hibernate.dialect.MySQL5Dialect
#     generate-ddl: true
#     show-sql: true
#     hibernate:
#       ddl-auto: create

  datasource:
    username: sa
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    password: ''
  h2:
    console:
      enabled: 'true'
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka/
  instance:
    hostname: localhost

jwt:
  secret: admin